Updated workflows

diff --git a/.github/workflows/build.pr.yaml b/.github/workflows/build.pr.yaml
--- a/.github/workflows/build.pr.yaml
+++ b/.github/workflows/build.pr.yaml
@@ -5,8 +5,8 @@ on:
     branches: [main]
 
 jobs:
-  build-storybook:
-    name: Build storybook
+  test:
+    name: Pull request build and pre-deployment checks
     runs-on: ubuntu-latest
     steps:
 
@@ -17,43 +17,35 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 22
+          cache: 'yarn'
 
       - name: Install dependencies
         run: |
           yarn install
+
+      # Prettify code and commit if changes
+      - name: Format code
+        run: |
+          yarn run format
+          git config --global user.name "GitHub Action"
+          if ! git diff --quiet; then
+            git add .
+            git commit -m "chore: format code"
+            git push
+          fi
 
       - name: Build storybook
         run: |
           yarn run build:storybook
 
-      - name: Install rclone
-        run: |
-          curl https://rclone.org/install.sh | sudo bash
-
-  build-packages:
-    name: Prepare releases
-    runs-on: ubuntu-latest
-    env:
-      # Ensure that Chalk uses colors in the output
-      FORCE_COLOR: 2
-    steps:
-
-      - name: Check out repository
-        uses: actions/checkout@v4
-
-      - name: Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 22
-
-      - name: Install dependencies
-        run: |
-          yarn install
-
       - name: Build all packages
         run: |
           yarn run build
 
+      # Get release status, this helps to determine if we are ready to publish
+      # in cases when we are updating package versions.
+
+      # We expect this to fail if a release will be incorrect on merging the PR.
       - name: Get release status
         run: |
           yarn run status 
